#!/bin/bash
# Check for compiled library
if [ -f ftagmgrlib.o ]; then
    echo Compiled object exists, deleting.
    rm -v ftagmgrlib.o
fi
if [ -f ftagmgrlib.a ]; then
    echo Library exists, deleting.
    rm -v ftagmgrlib.a
fi
# Recompile
echo Compiling...
g++ -c ftagmgrlib.cpp
# Check compilation result
if [ -f ftagmgrlib.o ]; then
    echo Creating library...
    ar r ftagmgrlib.a ftagmgrlib.o
    if [ -f ftagmgrlib.a ]; then
        echo Deleting object file.
        rm -v ftagmgrlib.o
        echo -e "\e[38;5;2mCompilation successful! \e[0m"
    else
        echo -e "\e[38;5;1mCouldn't create library! \e[0m"
        echo -e "\e[38;5;3mCheck if \e[38;5;5mar r ftagmgrlib.a ftagmgrlib.o\e[38;5;3m works\e[0m"
    fi
else
    echo -e "\e[38;5;1mCompilation failed, cannot create library! \e[0m"
    echo -e "\e[38;5;3mCheck if \e[38;5;5mg++ -c ftagmgrlib.cpp\e[38;5;3m works\e[0m"
fi